version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt"}}

      # Install dependencies
      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r tests/requirements.txt
            pip install pytest-html

      # Cache dependencies
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}--{{ checksum "tests/requirements.txt"}}

      # Run tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd ~/repo
            yapf --diff --exclude venv/ --exclude .git/ -r .
            FORMATTING_ERRORS=$?
            SOURCE_FILES=`find ./redeem -name \*.cpp -type f -or -name \*.h -type f`
            for SOURCE_FILE in $SOURCE_FILES
            do
              export FORMATTING_ISSUE_COUNT=`clang-format -output-replacements-xml $SOURCE_FILE | grep offset | wc -l`
              if [ "$FORMATTING_ISSUE_COUNT" -gt "0" ]; then
                echo "Source file $SOURCE_FILE contains formatting issues. Please use clang-format tool to resolve found issues."
                FORMATTING_ERRORS=1
              fi
            done
            exit $FORMATTING_ERRORS
